#!/usr/bin/env node
// Generates app/tokens.generated.css from the single source of truth at
// _design/tokens.json (repo root). Run automatically via `predev`/`prebuild`
// npm scripts so the CSS can never drift from the tokens file.
//
// Do NOT hand-edit app/tokens.generated.css — edit _design/tokens.json (owned
// by the design-extraction agent) or, if you need a web-only alias, add it
// in the EXTRA section below.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../../..");
// Prefer the monorepo source of truth; fall back to a vendored copy that ships
// inside apps/web for standalone deploys (e.g. Railway with rootDirectory=apps/web,
// where the repo-root _design/ sibling is outside the build context).
const TOKENS_CANDIDATES = [
  path.join(REPO_ROOT, "_design", "tokens.json"),
  path.join(__dirname, "..", "tokens.source.json"),
];
const TOKENS_PATH = TOKENS_CANDIDATES.find(existsSync) ?? TOKENS_CANDIDATES[0];
const OUT_PATH = path.join(__dirname, "..", "app", "tokens.generated.css");

const tokens = JSON.parse(readFileSync(TOKENS_PATH, "utf-8"));

const lines = [];
lines.push("/* AUTO-GENERATED by scripts/generate-tokens.mjs from _design/tokens.json. DO NOT EDIT BY HAND. */");
lines.push(":root {");

// --- Brand accent ramp ---
const b = tokens.color.brand;
lines.push(`  --accent: ${b.accent};`);
lines.push(`  --accent-hover: ${b.accentHover};`);
lines.push(`  --accent-pressed: ${b.accentPressed};`);
lines.push(`  --accent-light: ${b.accentLight};`);
lines.push(`  --accent-subtle-bg-light: ${b.accentSubtleBgLight};`);
lines.push(`  --accent-subtle-border-light: ${b.accentSubtleBorderLight};`);
lines.push(`  --accent-subtle-bg-dark: ${b.accentSubtleBgDark};`);
lines.push(`  --accent-text-on-tint: ${b.accentTextOnTint};`);
lines.push(`  --accent-on-dark-border: ${b.accentOnDarkBorder};`);
lines.push(`  --accent-disabled: ${b.accentDisabled};`);
lines.push(`  --on-accent: ${b.onAccent};`);
for (const [k, v] of Object.entries(b.accentAlpha)) {
  lines.push(`  --accent-alpha-${k}: ${v};`);
}

// --- Pro / secondary accent ---
const pro = tokens.color.pro;
lines.push(`  --pro: ${pro.light};`);
lines.push(`  --pro-dark: ${pro.dark};`);
lines.push(`  --pro-text-on-tint: ${pro.textOnTintLight};`);
lines.push(`  --pro-tint-bg: ${pro.tintBgLight};`);
lines.push(`  --pro-tint-border: ${pro.tintBorderLight};`);

// --- Uncertain-detection chip ---
const uc = tokens.color.uncertainDetection.light;
lines.push(`  --uncertain-bg: ${uc.bg};`);
lines.push(`  --uncertain-border: ${uc.border};`);
lines.push(`  --uncertain-text: ${uc.text};`);

// --- Glass dark theme (canonical / primary theme) ---
const glassDark = tokens.color.themes.glassDark;
lines.push(`  --bg-gradient: ${glassDark.bgGradient};`);
lines.push(`  --bg-gradient-flat: ${glassDark.bgGradientFlat};`);
lines.push(`  --bloom-accent: ${glassDark.bloomAccent};`);
lines.push(`  --bloom-pro: ${glassDark.bloomPro};`);
lines.push(`  --text-primary: ${glassDark.textPrimary};`);
lines.push(`  --text-base: ${glassDark.textBase};`);
for (const [k, v] of Object.entries(glassDark.textAlpha)) {
  lines.push(`  --text-alpha-${k}: ${v};`);
}
lines.push(`  --text-on-cream: ${glassDark.textOnCream};`);

const g = glassDark.glass;
lines.push(`  --panel-bg-low: ${g.panelBg.low};`);
lines.push(`  --panel-bg-mid: ${g.panelBg.mid};`);
lines.push(`  --panel-bg-high: ${g.panelBg.high};`);
lines.push(`  --panel-bg-hero: ${g.panelBg.hero};`);
lines.push(`  --nav-bar-bg: ${g.navBarBg};`);
lines.push(`  --border-subtle: ${g.border.subtle};`);
lines.push(`  --border-hero: ${g.border.hero};`);
lines.push(`  --border-button: ${g.border.button};`);
lines.push(`  --shine-subtle: ${g.innerShine.subtle};`);
lines.push(`  --shine-mid: ${g.innerShine.mid};`);
lines.push(`  --shine-hero: ${g.innerShine.hero};`);
lines.push(`  --blur-sm: ${g.blur.sm};`);
lines.push(`  --blur-md: ${g.blur.md};`);
lines.push(`  --blur-lg: ${g.blur.lg};`);
lines.push(`  --blur-xl: ${g.blur.xl};`);
lines.push(`  --blur-2xl: ${g.blur["2xl"]};`);
lines.push(`  --blur-nav: ${g.blur.navBar};`);
lines.push(`  --shadow-button: ${g.outerShadow.button};`);
lines.push(`  --shadow-button-lg: ${g.outerShadow.buttonLg};`);
lines.push(`  --shadow-hero: ${g.outerShadow.hero};`);
lines.push(`  --shadow-hero-lg: ${g.outerShadow.heroLg};`);
lines.push(`  --shadow-nav: ${g.outerShadow.navBar};`);
lines.push(`  --shadow-device-bezel: ${g.outerShadow.deviceBezel};`);

// --- Typography ---
const t = tokens.typography;
lines.push(`  --font-display: ${t.fontFamilies.display};`);
lines.push(`  --font-ui: ${t.fontFamilies.ui};`);
lines.push(`  --font-mono: ${t.fontFamilies.mono};`);

// --- Spacing ---
for (const [k, v] of Object.entries(tokens.spacing)) {
  if (typeof v === "number") lines.push(`  --space-${k}: ${v}px;`);
}
lines.push(`  --sidebar-width: ${tokens.spacing.webSidebarWidth}px;`);

// --- Radii ---
for (const [k, v] of Object.entries(tokens.radii)) {
  lines.push(`  --radius-${k}: ${v}px;`);
}

// --- Elevation ---
for (const [k, v] of Object.entries(tokens.elevation)) {
  lines.push(`  --elevation-${k}: ${v.boxShadow};`);
}

// --- Motion ---
lines.push(`  --ease-organic: ${tokens.motion.easingRecommended};`);
lines.push(`  --duration-micro: ${tokens.motion.durationMicroMs[1]}ms;`);
lines.push(`  --duration-screen: ${tokens.motion.durationScreenMs[1]}ms;`);

// --- EXTRA (web-only aliases not present in tokens.json) ---
lines.push(`  --danger: ${pro.light};`);

lines.push("}");
lines.push("");

mkdirSync(path.dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, lines.join("\n") + "\n", "utf-8");
console.log(`[generate-tokens] wrote ${lines.length} lines to ${path.relative(process.cwd(), OUT_PATH)}`);
